import { Inter } from "next/font/google";
import "./globals.css";
import "./test.css";
import "./colors.css";
import "./menu.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Junting's Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
